### ISSUE TITLE
/lockfile.rb:83 warning: optional boolean argument is obsoleted

### ISSUE THREAD

**Issue by x-itec** [ahoward/lockfile#10]
16:23:55,856 ERROR [stderr](pool-1-thread-2) /usr/local/rvm/gems/jruby-1.7.8@test/gems/lockfile-2.1.0/lib/lockfile.rb:72 warning: optional boolean argument is obsoleted
16:23:55,857 ERROR [stderr](pool-1-thread-2) /usr/local/rvm/gems/jruby-1.7.8@test/gems/lockfile-2.1.0/lib/lockfile.rb:73 warning: optional boolean argument is obsoleted
16:23:55,857 ERROR [stderr](pool-1-thread-2) /usr/local/rvm/gems/jruby-1.7.8@test/gems/lockfile-2.1.0/lib/lockfile.rb:74 warning: optional boolean argument is obsoleted
16:23:55,858 ERROR [stderr](pool-1-thread-2) /usr/local/rvm/gems/jruby-1.7.8@test/gems/lockfile-2.1.0/lib/lockfile.rb:75 warning: optional boolean argument is obsoleted
16:23:55,858 ERROR [stderr](pool-1-thread-2) /usr/local/rvm/gems/jruby-1.7.8@test/gems/lockfile-2.1.0/lib/lockfile.rb:76 warning: optional boolean argument is obsoleted
16:23:55,859 ERROR [stderr](pool-1-thread-2) /usr/local/rvm/gems/jruby-1.7.8@test/gems/lockfile-2.1.0/lib/lockfile.rb:77 warning: optional boolean argument is obsoleted
16:23:55,859 ERROR [stderr](pool-1-thread-2) /usr/local/rvm/gems/jruby-1.7.8@test/gems/lockfile-2.1.0/lib/lockfile.rb:78 warning: optional boolean argument is obsoleted
16:23:55,860 ERROR [stderr](pool-1-thread-2) /usr/local/rvm/gems/jruby-1.7.8@test/gems/lockfile-2.1.0/lib/lockfile.rb:79 warning: optional boolean argument is obsoleted
16:23:55,860 ERROR [stderr](pool-1-thread-2) /usr/local/rvm/gems/jruby-1.7.8@test/gems/lockfile-2.1.0/lib/lockfile.rb:80 warning: optional boolean argument is obsoleted
16:23:55,861 ERROR [stderr](pool-1-thread-2) /usr/local/rvm/gems/jruby-1.7.8@test/gems/lockfile-2.1.0/lib/lockfile.rb:81 warning: optional boolean argument is obsoleted
16:23:55,861 ERROR [stderr](pool-1-thread-2) /usr/local/rvm/gems/jruby-1.7.8@test/gems/lockfile-2.1.0/lib/lockfile.rb:82 warning: optional boolean argument is obsoleted
16:23:55,862 ERROR [stderr](pool-1-thread-2) /usr/local/rvm/gems/jruby-1.7.8@test/gems/lockfile-2.1.0/lib/lockfile.rb:83 warning: optional boolean argument is obsoleted
16:23:55,862 ERROR [stderr](pool-1-thread-2) /usr/local/rvm/gems/jruby-1.7.8@test/gems/lockfile-2.1.0/lib/lockfile.rb:84 warning: optional boolean argument is obsoleted
16:23:55,863 ERROR [stderr](pool-1-thread-2) /usr/local/rvm/gems/jruby-1.7.8@test/gems/lockfile-2.1.0/lib/lockfile.rb:85 warning: optional boolean argument is obsoleted

**Comment by donv** [comment]
Hi @x-itec !

Have you tried using master?

**Comment by x-itec** [comment]
Hi nope the gem is used by torquebox in this version (seems to be I don't know) is there anything I can do to test further?

**Comment by donv** [comment]
This pull request fixes the problem:  https://github.com/ahoward/lockfile/pull/8  You could point your Gemfile at that repository:  https://github.com/DatekWireless/lockfile.git

**Comment by x-itec** [comment]
excellent, works - good job
