### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bkabrda** [ahoward/lockfile#2]
Hi,
could you please state your license for this gem?

Thanks.

**Comment by avtobiff** [comment]
See http://codeforpeople.com/lib/license.txt .

I would prefer to see the license explicitly stated and shipped with the source.

Best,
Per

**Comment by nbibler** [comment]
:+1: For providing an explicit license.

RubyGems provides an interface for defining a library's license via the `.gemspec` with:

``` ruby
Gem::Specification.new do |spec|
  # ...
  spec.license       = "MIT"
  # ...
end
```

In this case, seemingly `spec.license = "Ruby"` would be appropriate if I'm understanding the above link correctly.

**Comment by ahoward** [comment]
in the gemfile now.
